var annotated_dup =
[
    [ "std", null, [
      [ "tuple_size< xt::const_array< T, N > >", "classstd_1_1tuple__size_3_01xt_1_1const__array_3_01_t_00_01_n_01_4_01_4.html", null ],
      [ "tuple_size< xt::fixed_shape< N... > >", "classstd_1_1tuple__size_3_01xt_1_1fixed__shape_3_01_n_8_8_8_01_4_01_4.html", null ],
      [ "tuple_size< xt::sequence_view< T, Start, End > >", "classstd_1_1tuple__size_3_01xt_1_1sequence__view_3_01_t_00_01_start_00_01_end_01_4_01_4.html", null ]
    ] ],
    [ "xt", "namespacext.html", [
      [ "check_policy", null, [
        [ "full", "structxt_1_1check__policy_1_1full.html", null ],
        [ "none", "structxt_1_1check__policy_1_1none.html", null ]
      ] ],
      [ "convolve_mode", null, [
        [ "full", "structxt_1_1convolve__mode_1_1full.html", null ],
        [ "valid", "structxt_1_1convolve__mode_1_1valid.html", null ]
      ] ],
      [ "evaluation_strategy", null, [
        [ "immediate_type", "structxt_1_1evaluation__strategy_1_1immediate__type.html", null ],
        [ "lazy_type", "structxt_1_1evaluation__strategy_1_1lazy__type.html", null ]
      ] ],
      [ "extension", null, [
        [ "expression_tag_and", "structxt_1_1extension_1_1expression__tag__and.html", null ],
        [ "expression_tag_and< T >", "structxt_1_1extension_1_1expression__tag__and_3_01_t_01_4.html", null ],
        [ "expression_tag_and< T, T >", "structxt_1_1extension_1_1expression__tag__and_3_01_t_00_01_t_01_4.html", null ],
        [ "expression_tag_and< T, xtensor_expression_tag >", "structxt_1_1extension_1_1expression__tag__and_3_01_t_00_01xtensor__expression__tag_01_4.html", null ],
        [ "expression_tag_and< T1, T... >", "structxt_1_1extension_1_1expression__tag__and_3_01_t1_00_01_t_8_8_8_01_4.html", null ],
        [ "expression_tag_and< xtensor_expression_tag, T >", "structxt_1_1extension_1_1expression__tag__and_3_01xtensor__expression__tag_00_01_t_01_4.html", null ],
        [ "expression_tag_and< xtensor_expression_tag, xtensor_expression_tag >", "structxt_1_1extension_1_1expression__tag__and_3_01xtensor__expression__tag_00_01xtensor__expression__tag_01_4.html", null ],
        [ "expression_tag_and<>", "structxt_1_1extension_1_1expression__tag__and_3_4.html", null ],
        [ "get_expression_tag", "structxt_1_1extension_1_1get__expression__tag.html", null ],
        [ "get_expression_tag< xtl::xoptional< T, B > >", "structxt_1_1extension_1_1get__expression__tag_3_01xtl_1_1xoptional_3_01_t_00_01_b_01_4_01_4.html", null ],
        [ "get_expression_tag_impl", "structxt_1_1extension_1_1get__expression__tag__impl.html", null ],
        [ "get_expression_tag_impl< E, void_t< typename std::decay_t< E >::expression_tag > >", "structxt_1_1extension_1_1get__expression__tag__impl_3_01_e_00_01void__t_3_01typename_01std_1_1de048c22abe806a8cb61aa0c08ab63f2de.html", null ],
        [ "xarray_adaptor_base", "structxt_1_1extension_1_1xarray__adaptor__base.html", null ],
        [ "xarray_adaptor_base< EC, L, SC, xoptional_expression_tag >", "structxt_1_1extension_1_1xarray__adaptor__base_3_01_e_c_00_01_l_00_01_s_c_00_01xoptional__expression__tag_01_4.html", null ],
        [ "xarray_adaptor_base< EC, L, SC, xtensor_expression_tag >", "structxt_1_1extension_1_1xarray__adaptor__base_3_01_e_c_00_01_l_00_01_s_c_00_01xtensor__expression__tag_01_4.html", null ],
        [ "xarray_adaptor_optional_traits", "structxt_1_1extension_1_1xarray__adaptor__optional__traits.html", null ],
        [ "xarray_container_base", "structxt_1_1extension_1_1xarray__container__base.html", null ],
        [ "xarray_container_base< EC, L, SC, xoptional_expression_tag >", "structxt_1_1extension_1_1xarray__container__base_3_01_e_c_00_01_l_00_01_s_c_00_01xoptional__expression__tag_01_4.html", null ],
        [ "xarray_container_base< EC, L, SC, xtensor_expression_tag >", "structxt_1_1extension_1_1xarray__container__base_3_01_e_c_00_01_l_00_01_s_c_00_01xtensor__expression__tag_01_4.html", null ],
        [ "xarray_container_optional_traits", "structxt_1_1extension_1_1xarray__container__optional__traits.html", null ],
        [ "xarray_optional_traits", "structxt_1_1extension_1_1xarray__optional__traits.html", null ],
        [ "xbroadcast_base", "structxt_1_1extension_1_1xbroadcast__base.html", null ],
        [ "xbroadcast_base_impl", "structxt_1_1extension_1_1xbroadcast__base__impl.html", null ],
        [ "xbroadcast_base_impl< xoptional_expression_tag, CT, X >", "structxt_1_1extension_1_1xbroadcast__base__impl_3_01xoptional__expression__tag_00_01_c_t_00_01_x_01_4.html", null ],
        [ "xbroadcast_base_impl< xtensor_expression_tag, CT, X >", "structxt_1_1extension_1_1xbroadcast__base__impl_3_01xtensor__expression__tag_00_01_c_t_00_01_x_01_4.html", null ],
        [ "xbroadcast_optional", "classxt_1_1extension_1_1xbroadcast__optional.html", null ],
        [ "xcontainer_optional_base", "classxt_1_1extension_1_1xcontainer__optional__base.html", null ],
        [ "xdynamic_view_base", "structxt_1_1extension_1_1xdynamic__view__base.html", null ],
        [ "xdynamic_view_base_impl", "structxt_1_1extension_1_1xdynamic__view__base__impl.html", null ],
        [ "xdynamic_view_base_impl< xoptional_expression_tag, CT, S, L, FST >", "structxt_1_1extension_1_1xdynamic__view__base__impl_3_01xoptional__expression__tag_00_01_c_t_00_01_s_00_01_l_00_01_f_s_t_01_4.html", null ],
        [ "xdynamic_view_base_impl< xtensor_expression_tag, CT, S, L, FST >", "structxt_1_1extension_1_1xdynamic__view__base__impl_3_01xtensor__expression__tag_00_01_c_t_00_01_s_00_01_l_00_01_f_s_t_01_4.html", null ],
        [ "xdynamic_view_optional", "classxt_1_1extension_1_1xdynamic__view__optional.html", null ],
        [ "xfunction_base", "structxt_1_1extension_1_1xfunction__base.html", null ],
        [ "xfunction_base_impl", "structxt_1_1extension_1_1xfunction__base__impl.html", null ],
        [ "xfunction_base_impl< xoptional_expression_tag, F, CT... >", "structxt_1_1extension_1_1xfunction__base__impl_3_01xoptional__expression__tag_00_01_f_00_01_c_t_8_8_8_01_4.html", null ],
        [ "xfunction_base_impl< xtensor_expression_tag, F, CT... >", "structxt_1_1extension_1_1xfunction__base__impl_3_01xtensor__expression__tag_00_01_f_00_01_c_t_8_8_8_01_4.html", null ],
        [ "xfunction_optional_base", "classxt_1_1extension_1_1xfunction__optional__base.html", null ],
        [ "xfunctor_view_base", "structxt_1_1extension_1_1xfunctor__view__base.html", null ],
        [ "xfunctor_view_base_impl", "structxt_1_1extension_1_1xfunctor__view__base__impl.html", null ],
        [ "xfunctor_view_base_impl< xoptional_expression_tag, F, CT >", "structxt_1_1extension_1_1xfunctor__view__base__impl_3_01xoptional__expression__tag_00_01_f_00_01_c_t_01_4.html", null ],
        [ "xfunctor_view_base_impl< xtensor_expression_tag, F, CT >", "structxt_1_1extension_1_1xfunctor__view__base__impl_3_01xtensor__expression__tag_00_01_f_00_01_c_t_01_4.html", null ],
        [ "xfunctor_view_optional", "classxt_1_1extension_1_1xfunctor__view__optional.html", null ],
        [ "xgenerator_base", "structxt_1_1extension_1_1xgenerator__base.html", null ],
        [ "xgenerator_base_impl", "structxt_1_1extension_1_1xgenerator__base__impl.html", null ],
        [ "xgenerator_base_impl< xoptional_expression_tag, F, R, S >", "structxt_1_1extension_1_1xgenerator__base__impl_3_01xoptional__expression__tag_00_01_f_00_01_r_00_01_s_01_4.html", null ],
        [ "xgenerator_base_impl< xtensor_expression_tag, F, R, S >", "structxt_1_1extension_1_1xgenerator__base__impl_3_01xtensor__expression__tag_00_01_f_00_01_r_00_01_s_01_4.html", null ],
        [ "xgenerator_optional", "classxt_1_1extension_1_1xgenerator__optional.html", null ],
        [ "xindex_view_base", "structxt_1_1extension_1_1xindex__view__base.html", null ],
        [ "xindex_view_base_impl", "structxt_1_1extension_1_1xindex__view__base__impl.html", null ],
        [ "xindex_view_base_impl< xoptional_expression_tag, CT, I >", "structxt_1_1extension_1_1xindex__view__base__impl_3_01xoptional__expression__tag_00_01_c_t_00_01_i_01_4.html", null ],
        [ "xindex_view_base_impl< xtensor_expression_tag, CT, I >", "structxt_1_1extension_1_1xindex__view__base__impl_3_01xtensor__expression__tag_00_01_c_t_00_01_i_01_4.html", null ],
        [ "xindex_view_optional", "classxt_1_1extension_1_1xindex__view__optional.html", null ],
        [ "xoptional_empty_base", "classxt_1_1extension_1_1xoptional__empty__base.html", null ],
        [ "xreducer_base", "structxt_1_1extension_1_1xreducer__base.html", null ],
        [ "xreducer_base_impl", "structxt_1_1extension_1_1xreducer__base__impl.html", null ],
        [ "xreducer_base_impl< xoptional_expression_tag, F, CT, X, O >", "structxt_1_1extension_1_1xreducer__base__impl_3_01xoptional__expression__tag_00_01_f_00_01_c_t_00_01_x_00_01_o_01_4.html", null ],
        [ "xreducer_base_impl< xtensor_expression_tag, F, CT, X, O >", "structxt_1_1extension_1_1xreducer__base__impl_3_01xtensor__expression__tag_00_01_f_00_01_c_t_00_01_x_00_01_o_01_4.html", null ],
        [ "xreducer_optional", "classxt_1_1extension_1_1xreducer__optional.html", null ],
        [ "xrepeat_base", "structxt_1_1extension_1_1xrepeat__base.html", null ],
        [ "xrepeat_base_impl", "structxt_1_1extension_1_1xrepeat__base__impl.html", null ],
        [ "xrepeat_base_impl< xoptional_expression_tag, CT, X >", "structxt_1_1extension_1_1xrepeat__base__impl_3_01xoptional__expression__tag_00_01_c_t_00_01_x_01_4.html", null ],
        [ "xrepeat_base_impl< xtensor_expression_tag, CT, X >", "structxt_1_1extension_1_1xrepeat__base__impl_3_01xtensor__expression__tag_00_01_c_t_00_01_x_01_4.html", null ],
        [ "xrepeat_optional", "classxt_1_1extension_1_1xrepeat__optional.html", null ],
        [ "xscalar_base", "structxt_1_1extension_1_1xscalar__base.html", null ],
        [ "xscalar_base_impl", "structxt_1_1extension_1_1xscalar__base__impl.html", null ],
        [ "xscalar_base_impl< xoptional_expression_tag, CT >", "structxt_1_1extension_1_1xscalar__base__impl_3_01xoptional__expression__tag_00_01_c_t_01_4.html", null ],
        [ "xscalar_base_impl< xtensor_expression_tag, CT >", "structxt_1_1extension_1_1xscalar__base__impl_3_01xtensor__expression__tag_00_01_c_t_01_4.html", null ],
        [ "xscalar_optional_base", "classxt_1_1extension_1_1xscalar__optional__base.html", null ],
        [ "xscalar_optional_traits", "structxt_1_1extension_1_1xscalar__optional__traits.html", null ],
        [ "xstrided_view_base", "structxt_1_1extension_1_1xstrided__view__base.html", null ],
        [ "xstrided_view_base_impl", "structxt_1_1extension_1_1xstrided__view__base__impl.html", null ],
        [ "xstrided_view_base_impl< xoptional_expression_tag, CT, S, L, FST >", "structxt_1_1extension_1_1xstrided__view__base__impl_3_01xoptional__expression__tag_00_01_c_t_00_01_s_00_01_l_00_01_f_s_t_01_4.html", null ],
        [ "xstrided_view_base_impl< xtensor_expression_tag, CT, S, L, FST >", "structxt_1_1extension_1_1xstrided__view__base__impl_3_01xtensor__expression__tag_00_01_c_t_00_01_s_00_01_l_00_01_f_s_t_01_4.html", null ],
        [ "xstrided_view_optional", "classxt_1_1extension_1_1xstrided__view__optional.html", null ],
        [ "xtensor_adaptor_base", "structxt_1_1extension_1_1xtensor__adaptor__base.html", null ],
        [ "xtensor_adaptor_base< EC, N, L, xoptional_expression_tag >", "structxt_1_1extension_1_1xtensor__adaptor__base_3_01_e_c_00_01_n_00_01_l_00_01xoptional__expression__tag_01_4.html", null ],
        [ "xtensor_adaptor_base< EC, N, L, xtensor_expression_tag >", "structxt_1_1extension_1_1xtensor__adaptor__base_3_01_e_c_00_01_n_00_01_l_00_01xtensor__expression__tag_01_4.html", null ],
        [ "xtensor_adaptor_optional_traits", "structxt_1_1extension_1_1xtensor__adaptor__optional__traits.html", null ],
        [ "xtensor_container_base", "structxt_1_1extension_1_1xtensor__container__base.html", null ],
        [ "xtensor_container_base< EC, N, L, xoptional_expression_tag >", "structxt_1_1extension_1_1xtensor__container__base_3_01_e_c_00_01_n_00_01_l_00_01xoptional__expression__tag_01_4.html", null ],
        [ "xtensor_container_base< EC, N, L, xtensor_expression_tag >", "structxt_1_1extension_1_1xtensor__container__base_3_01_e_c_00_01_n_00_01_l_00_01xtensor__expression__tag_01_4.html", null ],
        [ "xtensor_container_optional_traits", "structxt_1_1extension_1_1xtensor__container__optional__traits.html", null ],
        [ "xtensor_empty_base", "structxt_1_1extension_1_1xtensor__empty__base.html", null ],
        [ "xtensor_optional_traits", "structxt_1_1extension_1_1xtensor__optional__traits.html", null ],
        [ "xtensor_view_base", "structxt_1_1extension_1_1xtensor__view__base.html", null ],
        [ "xtensor_view_base< EC, N, L, xoptional_expression_tag >", "structxt_1_1extension_1_1xtensor__view__base_3_01_e_c_00_01_n_00_01_l_00_01xoptional__expression__tag_01_4.html", null ],
        [ "xtensor_view_base< EC, N, L, xtensor_expression_tag >", "structxt_1_1extension_1_1xtensor__view__base_3_01_e_c_00_01_n_00_01_l_00_01xtensor__expression__tag_01_4.html", null ],
        [ "xtensor_view_optional_traits", "structxt_1_1extension_1_1xtensor__view__optional__traits.html", null ],
        [ "xview_base", "structxt_1_1extension_1_1xview__base.html", null ],
        [ "xview_base_impl", "structxt_1_1extension_1_1xview__base__impl.html", null ],
        [ "xview_base_impl< xoptional_expression_tag, CT, S... >", "structxt_1_1extension_1_1xview__base__impl_3_01xoptional__expression__tag_00_01_c_t_00_01_s_8_8_8_01_4.html", null ],
        [ "xview_base_impl< xtensor_expression_tag, CT, S... >", "structxt_1_1extension_1_1xview__base__impl_3_01xtensor__expression__tag_00_01_c_t_00_01_s_8_8_8_01_4.html", null ],
        [ "xview_optional", "classxt_1_1extension_1_1xview__optional.html", null ]
      ] ],
      [ "math", null, [
        [ "abs_fun", "structxt_1_1math_1_1abs__fun.html", null ],
        [ "acos_fun", "structxt_1_1math_1_1acos__fun.html", null ],
        [ "acosh_fun", "structxt_1_1math_1_1acosh__fun.html", null ],
        [ "arg_fun", "structxt_1_1math_1_1arg__fun.html", null ],
        [ "asin_fun", "structxt_1_1math_1_1asin__fun.html", null ],
        [ "asinh_fun", "structxt_1_1math_1_1asinh__fun.html", null ],
        [ "atan2_fun", "structxt_1_1math_1_1atan2__fun.html", null ],
        [ "atan_fun", "structxt_1_1math_1_1atan__fun.html", null ],
        [ "atanh_fun", "structxt_1_1math_1_1atanh__fun.html", null ],
        [ "cbrt_fun", "structxt_1_1math_1_1cbrt__fun.html", null ],
        [ "ceil_fun", "structxt_1_1math_1_1ceil__fun.html", null ],
        [ "clamp_fun", "structxt_1_1math_1_1clamp__fun.html", null ],
        [ "conj_fun", "structxt_1_1math_1_1conj__fun.html", null ],
        [ "conj_impl_fun", "structxt_1_1math_1_1conj__impl__fun.html", null ],
        [ "cos_fun", "structxt_1_1math_1_1cos__fun.html", null ],
        [ "cosh_fun", "structxt_1_1math_1_1cosh__fun.html", null ],
        [ "deg2rad", "structxt_1_1math_1_1deg2rad.html", null ],
        [ "erf_fun", "structxt_1_1math_1_1erf__fun.html", null ],
        [ "erfc_fun", "structxt_1_1math_1_1erfc__fun.html", null ],
        [ "exp2_fun", "structxt_1_1math_1_1exp2__fun.html", null ],
        [ "exp_fun", "structxt_1_1math_1_1exp__fun.html", null ],
        [ "expm1_fun", "structxt_1_1math_1_1expm1__fun.html", null ],
        [ "fabs_fun", "structxt_1_1math_1_1fabs__fun.html", null ],
        [ "fdim_fun", "structxt_1_1math_1_1fdim__fun.html", null ],
        [ "floor_fun", "structxt_1_1math_1_1floor__fun.html", null ],
        [ "fma_fun", "structxt_1_1math_1_1fma__fun.html", null ],
        [ "fmax_fun", "structxt_1_1math_1_1fmax__fun.html", null ],
        [ "fmin_fun", "structxt_1_1math_1_1fmin__fun.html", null ],
        [ "fmod_fun", "structxt_1_1math_1_1fmod__fun.html", null ],
        [ "hypot_fun", "structxt_1_1math_1_1hypot__fun.html", null ],
        [ "isfinite_fun", "structxt_1_1math_1_1isfinite__fun.html", null ],
        [ "isinf_fun", "structxt_1_1math_1_1isinf__fun.html", null ],
        [ "isnan_fun", "structxt_1_1math_1_1isnan__fun.html", null ],
        [ "lgamma_fun", "structxt_1_1math_1_1lgamma__fun.html", null ],
        [ "log10_fun", "structxt_1_1math_1_1log10__fun.html", null ],
        [ "log1p_fun", "structxt_1_1math_1_1log1p__fun.html", null ],
        [ "log2_fun", "structxt_1_1math_1_1log2__fun.html", null ],
        [ "log_fun", "structxt_1_1math_1_1log__fun.html", null ],
        [ "maximum", "structxt_1_1math_1_1maximum.html", null ],
        [ "minimum", "structxt_1_1math_1_1minimum.html", null ],
        [ "nearbyint_fun", "structxt_1_1math_1_1nearbyint__fun.html", null ],
        [ "norm_fun", "structxt_1_1math_1_1norm__fun.html", null ],
        [ "pow_fun", "structxt_1_1math_1_1pow__fun.html", null ],
        [ "rad2deg", "structxt_1_1math_1_1rad2deg.html", null ],
        [ "remainder_fun", "structxt_1_1math_1_1remainder__fun.html", null ],
        [ "rint_fun", "structxt_1_1math_1_1rint__fun.html", null ],
        [ "round_fun", "structxt_1_1math_1_1round__fun.html", null ],
        [ "sign_fun", "structxt_1_1math_1_1sign__fun.html", null ],
        [ "sign_impl", "structxt_1_1math_1_1sign__impl.html", null ],
        [ "sign_impl< xtl::xoptional< T, B > >", "structxt_1_1math_1_1sign__impl_3_01xtl_1_1xoptional_3_01_t_00_01_b_01_4_01_4.html", null ],
        [ "sin_fun", "structxt_1_1math_1_1sin__fun.html", null ],
        [ "sinh_fun", "structxt_1_1math_1_1sinh__fun.html", null ],
        [ "sqrt_fun", "structxt_1_1math_1_1sqrt__fun.html", null ],
        [ "tan_fun", "structxt_1_1math_1_1tan__fun.html", null ],
        [ "tanh_fun", "structxt_1_1math_1_1tanh__fun.html", null ],
        [ "tgamma_fun", "structxt_1_1math_1_1tgamma__fun.html", null ],
        [ "trunc_fun", "structxt_1_1math_1_1trunc__fun.html", null ]
      ] ],
      [ "placeholders", null, [
        [ "rangemaker", "structxt_1_1placeholders_1_1rangemaker.html", null ],
        [ "rangemaker< A, B >", "structxt_1_1placeholders_1_1rangemaker_3_01_a_00_01_b_01_4.html", null ],
        [ "rangemaker< A, B, C >", "structxt_1_1placeholders_1_1rangemaker_3_01_a_00_01_b_00_01_c_01_4.html", null ],
        [ "xtuph", "structxt_1_1placeholders_1_1xtuph.html", null ]
      ] ],
      [ "print_options", null, [
        [ "edge_items", "classxt_1_1print__options_1_1edge__items.html", null ],
        [ "line_width", "classxt_1_1print__options_1_1line__width.html", null ],
        [ "precision", "classxt_1_1print__options_1_1precision.html", null ],
        [ "print_options_impl", "structxt_1_1print__options_1_1print__options__impl.html", null ],
        [ "threshold", "classxt_1_1print__options_1_1threshold.html", null ]
      ] ],
      [ "strided_assign_detail", null, [
        [ "check_strides_functor", "structxt_1_1strided__assign__detail_1_1check__strides__functor.html", null ],
        [ "idx_tools", "structxt_1_1strided__assign__detail_1_1idx__tools.html", null ],
        [ "idx_tools< layout_type::column_major >", "structxt_1_1strided__assign__detail_1_1idx__tools_3_01layout__type_1_1column__major_01_4.html", null ],
        [ "idx_tools< layout_type::row_major >", "structxt_1_1strided__assign__detail_1_1idx__tools_3_01layout__type_1_1row__major_01_4.html", null ],
        [ "loop_sizes_t", "structxt_1_1strided__assign__detail_1_1loop__sizes__t.html", null ]
      ] ],
      [ "traits_detail", null, [
        [ "norm_of_array_elements_impl", "structxt_1_1traits__detail_1_1norm__of__array__elements__impl.html", null ],
        [ "norm_of_array_elements_impl< long double, false, true >", "structxt_1_1traits__detail_1_1norm__of__array__elements__impl_3_01long_01double_00_01false_00_01true_01_4.html", null ],
        [ "norm_of_array_elements_impl< T, false, false >", "structxt_1_1traits__detail_1_1norm__of__array__elements__impl_3_01_t_00_01false_00_01false_01_4.html", null ],
        [ "norm_of_array_elements_impl< T, false, true >", "structxt_1_1traits__detail_1_1norm__of__array__elements__impl_3_01_t_00_01false_00_01true_01_4.html", null ],
        [ "norm_of_array_elements_impl< T, true, false >", "structxt_1_1traits__detail_1_1norm__of__array__elements__impl_3_01_t_00_01true_00_01false_01_4.html", null ],
        [ "norm_of_array_elements_impl< void *, false, false >", "structxt_1_1traits__detail_1_1norm__of__array__elements__impl_3_01void_01_5_00_01false_00_01false_01_4.html", null ],
        [ "norm_of_scalar_impl", "structxt_1_1traits__detail_1_1norm__of__scalar__impl.html", null ],
        [ "norm_of_scalar_impl< T, false >", "structxt_1_1traits__detail_1_1norm__of__scalar__impl_3_01_t_00_01false_01_4.html", null ],
        [ "norm_of_scalar_impl< T, true >", "structxt_1_1traits__detail_1_1norm__of__scalar__impl_3_01_t_00_01true_01_4.html", null ],
        [ "norm_of_vector_impl", "structxt_1_1traits__detail_1_1norm__of__vector__impl.html", null ],
        [ "norm_type_base", "structxt_1_1traits__detail_1_1norm__type__base.html", null ]
      ] ],
      [ "acquire_ownership", "structxt_1_1acquire__ownership.html", null ],
      [ "aligned_array", "classxt_1_1aligned__array.html", null ],
      [ "aligned_mode", "structxt_1_1aligned__mode.html", null ],
      [ "big_promote_value_type", "structxt_1_1big__promote__value__type.html", null ],
      [ "broadcast_error", "classxt_1_1broadcast__error.html", null ],
      [ "buffer_inner_types", "structxt_1_1buffer__inner__types.html", null ],
      [ "buffer_inner_types< xbuffer_adaptor< CP, O, A > >", "structxt_1_1buffer__inner__types_3_01xbuffer__adaptor_3_01_c_p_00_01_o_00_01_a_01_4_01_4.html", null ],
      [ "buffer_inner_types< xiterator_adaptor< I, CI > >", "structxt_1_1buffer__inner__types_3_01xiterator__adaptor_3_01_i_00_01_c_i_01_4_01_4.html", null ],
      [ "buffer_inner_types< xiterator_owner_adaptor< C, IG > >", "structxt_1_1buffer__inner__types_3_01xiterator__owner__adaptor_3_01_c_00_01_i_g_01_4_01_4.html", null ],
      [ "can_assign", "structxt_1_1can__assign.html", null ],
      [ "can_assign< xstrided_view< CT, S, L, FST >, RHS >", "structxt_1_1can__assign_3_01xstrided__view_3_01_c_t_00_01_s_00_01_l_00_01_f_s_t_01_4_00_01_r_h_s_01_4.html", null ],
      [ "check_strides_overlap", "structxt_1_1check__strides__overlap.html", null ],
      [ "check_strides_overlap< layout_type::column_major >", "structxt_1_1check__strides__overlap_3_01layout__type_1_1column__major_01_4.html", null ],
      [ "check_strides_overlap< layout_type::row_major >", "structxt_1_1check__strides__overlap_3_01layout__type_1_1row__major_01_4.html", null ],
      [ "common_difference_type", "structxt_1_1common__difference__type.html", null ],
      [ "common_difference_type<>", "structxt_1_1common__difference__type_3_4.html", null ],
      [ "common_size_type", "structxt_1_1common__size__type.html", null ],
      [ "common_size_type<>", "structxt_1_1common__size__type_3_4.html", null ],
      [ "common_tensor_type", "structxt_1_1common__tensor__type.html", null ],
      [ "common_value_type", "structxt_1_1common__value__type.html", null ],
      [ "concatenate_error", "classxt_1_1concatenate__error.html", null ],
      [ "conditional_cast_functor", "structxt_1_1conditional__cast__functor.html", null ],
      [ "conditional_cast_functor< false, T >", "structxt_1_1conditional__cast__functor_3_01false_00_01_t_01_4.html", null ],
      [ "conditional_cast_functor< true, T >", "structxt_1_1conditional__cast__functor_3_01true_00_01_t_01_4.html", null ],
      [ "const_array", "structxt_1_1const__array.html", null ],
      [ "const_value", "structxt_1_1const__value.html", null ],
      [ "const_xclosure", "structxt_1_1const__xclosure.html", null ],
      [ "const_xclosure< E, disable_xexpression< std::decay_t< E > > >", "structxt_1_1const__xclosure_3_01_e_00_01disable__xexpression_3_01std_1_1decay__t_3_01_e_01_4_01_4_01_4.html", null ],
      [ "const_xclosure< xshared_expression< E > &, std::enable_if_t< true > >", "structxt_1_1const__xclosure_3_01xshared__expression_3_01_e_01_4_01_6_00_01std_1_1enable__if__t_3_01true_01_4_01_4.html", null ],
      [ "container_simd_return_type", "structxt_1_1container__simd__return__type.html", null ],
      [ "decay_all", "structxt_1_1decay__all.html", null ],
      [ "decay_all< S< X... > >", "structxt_1_1decay__all_3_01_s_3_01_x_8_8_8_01_4_01_4.html", null ],
      [ "disable_indexed_stepper", "structxt_1_1disable__indexed__stepper.html", null ],
      [ "driven_align_mode", "structxt_1_1driven__align__mode.html", null ],
      [ "enable_indexed_stepper", "structxt_1_1enable__indexed__stepper.html", null ],
      [ "filter_fixed_shape", "structxt_1_1filter__fixed__shape.html", null ],
      [ "fixed_shape", "classxt_1_1fixed__shape.html", null ],
      [ "fixed_xreducer_shape_type", "structxt_1_1fixed__xreducer__shape__type.html", null ],
      [ "fixed_xreducer_shape_type< fixed_shape< I... >, fixed_shape< J... > >", "structxt_1_1fixed__xreducer__shape__type_3_01fixed__shape_3_01_i_8_8_8_01_4_00_01fixed__shape_3_01_j_8_8_8_01_4_01_4.html", null ],
      [ "forbid_simd", "structxt_1_1forbid__simd.html", null ],
      [ "forbid_simd< const std::vector< bool, A > >", "structxt_1_1forbid__simd_3_01const_01std_1_1vector_3_01bool_00_01_a_01_4_01_4.html", null ],
      [ "forbid_simd< const xtl::xdynamic_bitset< B, A > >", "structxt_1_1forbid__simd_3_01const_01xtl_1_1xdynamic__bitset_3_01_b_00_01_a_01_4_01_4.html", null ],
      [ "forbid_simd< std::vector< bool, A > >", "structxt_1_1forbid__simd_3_01std_1_1vector_3_01bool_00_01_a_01_4_01_4.html", null ],
      [ "forbid_simd< xtl::xdynamic_bitset< B, A > >", "structxt_1_1forbid__simd_3_01xtl_1_1xdynamic__bitset_3_01_b_00_01_a_01_4_01_4.html", null ],
      [ "get_init_type", "structxt_1_1get__init__type.html", null ],
      [ "get_init_type< V, fixed_shape< X... > >", "structxt_1_1get__init__type_3_01_v_00_01fixed__shape_3_01_x_8_8_8_01_4_01_4.html", null ],
      [ "get_rank", "structxt_1_1get__rank.html", null ],
      [ "get_rank< E, decltype((void) E::rank, void())>", "structxt_1_1get__rank_3_01_e_00_01decltype_07_07void_08_01_e_1_1rank_00_01void_07_08_08_4.html", null ],
      [ "get_strides_type", "structxt_1_1get__strides__type.html", null ],
      [ "get_strides_type< fixed_shape< I... > >", "structxt_1_1get__strides__type_3_01fixed__shape_3_01_i_8_8_8_01_4_01_4.html", null ],
      [ "get_strides_type< xbuffer_adaptor< CP, O, A > >", "structxt_1_1get__strides__type_3_01xbuffer__adaptor_3_01_c_p_00_01_o_00_01_a_01_4_01_4.html", null ],
      [ "get_value_type", "structxt_1_1get__value__type.html", null ],
      [ "get_value_type< T, void_t< typename T::value_type > >", "structxt_1_1get__value__type_3_01_t_00_01void__t_3_01typename_01_t_1_1value__type_01_4_01_4.html", null ],
      [ "has_assign_conversion", "structxt_1_1has__assign__conversion.html", null ],
      [ "has_assign_to", "structxt_1_1has__assign__to.html", null ],
      [ "has_assign_to< E1, E2, void_t< decltype(std::declval< const E2 & >().assign_to(std::declval< E1 & >()))> >", "structxt_1_1has__assign__to_3_01_e1_00_01_e2_00_01void__t_3_01decltype_07std_1_1declval_3_01cons059ed553ffd14856020f06c40d9ce771.html", null ],
      [ "has_data_interface", "structxt_1_1has__data__interface.html", null ],
      [ "has_data_interface< E, void_t< decltype(std::declval< E >().data())> >", "structxt_1_1has__data__interface_3_01_e_00_01void__t_3_01decltype_07std_1_1declval_3_01_e_01_4_07_08_8data_07_08_08_4_01_4.html", null ],
      [ "has_fixed_rank", "structxt_1_1has__fixed__rank.html", null ],
      [ "has_iterator_interface", "structxt_1_1has__iterator__interface.html", null ],
      [ "has_iterator_interface< E, void_t< decltype(std::declval< E >().begin())> >", "structxt_1_1has__iterator__interface_3_01_e_00_01void__t_3_01decltype_07std_1_1declval_3_01_e_01_4_07_08_8begin_07_08_08_4_01_4.html", null ],
      [ "has_memory_address", "structxt_1_1has__memory__address.html", null ],
      [ "has_memory_address< T, void_t< decltype(std::addressof(*std::declval< T >().begin()))> >", "structxt_1_1has__memory__address_3_01_t_00_01void__t_3_01decltype_07std_1_1addressof_07_5std_1_1e8ed49541169f10cfa05c619e2da0ead.html", null ],
      [ "has_rank", "structxt_1_1has__rank.html", null ],
      [ "has_sign_conversion", "structxt_1_1has__sign__conversion.html", null ],
      [ "has_simd_apply", "structxt_1_1has__simd__apply.html", null ],
      [ "has_simd_interface", "structxt_1_1has__simd__interface.html", null ],
      [ "has_simd_interface< xfunction< F, CT... >, T >", "structxt_1_1has__simd__interface_3_01xfunction_3_01_f_00_01_c_t_8_8_8_01_4_00_01_t_01_4.html", null ],
      [ "has_simd_interface< xfunctor_adaptor< F, CT >, T >", "structxt_1_1has__simd__interface_3_01xfunctor__adaptor_3_01_f_00_01_c_t_01_4_00_01_t_01_4.html", null ],
      [ "has_simd_interface< xfunctor_applier_base< D >, T >", "structxt_1_1has__simd__interface_3_01xfunctor__applier__base_3_01_d_01_4_00_01_t_01_4.html", null ],
      [ "has_simd_interface< xfunctor_view< F, CT >, T >", "structxt_1_1has__simd__interface_3_01xfunctor__view_3_01_f_00_01_c_t_01_4_00_01_t_01_4.html", null ],
      [ "has_simd_interface< xtensor_view< EC, N, L, Tag > >", "structxt_1_1has__simd__interface_3_01xtensor__view_3_01_e_c_00_01_n_00_01_l_00_01_tag_01_4_01_4.html", null ],
      [ "has_simd_type", "structxt_1_1has__simd__type.html", null ],
      [ "has_storage_type", "structxt_1_1has__storage__type.html", null ],
      [ "has_storage_type< T, void_t< typename xcontainer_inner_types< T >::storage_type > >", "structxt_1_1has__storage__type_3_01_t_00_01void__t_3_01typename_01xcontainer__inner__types_3_01_650a1762a9f827a241fdd5fca766bcf6.html", null ],
      [ "has_strides", "structxt_1_1has__strides.html", null ],
      [ "has_strides< E, void_t< decltype(std::declval< E >().strides())> >", "structxt_1_1has__strides_3_01_e_00_01void__t_3_01decltype_07std_1_1declval_3_01_e_01_4_07_08_8strides_07_08_08_4_01_4.html", null ],
      [ "index_from_shape", "structxt_1_1index__from__shape.html", null ],
      [ "initializer_dimension", "structxt_1_1initializer__dimension.html", null ],
      [ "inner_aligned_mode", "structxt_1_1inner__aligned__mode.html", null ],
      [ "inner_reference", "structxt_1_1inner__reference.html", null ],
      [ "invalid_type", "structxt_1_1invalid__type.html", null ],
      [ "is_chunked_t", "structxt_1_1is__chunked__t.html", null ],
      [ "is_contiguous_container", "structxt_1_1is__contiguous__container.html", null ],
      [ "is_contiguous_container< xiterator< St, S, L > >", "structxt_1_1is__contiguous__container_3_01xiterator_3_01_st_00_01_s_00_01_l_01_4_01_4.html", null ],
      [ "is_contiguous_container< xiterator_adaptor< I, CI > >", "structxt_1_1is__contiguous__container_3_01xiterator__adaptor_3_01_i_00_01_c_i_01_4_01_4.html", null ],
      [ "is_contiguous_container< xiterator_owner_adaptor< C, IG > >", "structxt_1_1is__contiguous__container_3_01xiterator__owner__adaptor_3_01_c_00_01_i_g_01_4_01_4.html", null ],
      [ "is_evaluation_strategy", "structxt_1_1is__evaluation__strategy.html", null ],
      [ "is_indexed_stepper", "structxt_1_1is__indexed__stepper.html", null ],
      [ "is_indexed_stepper< xindexed_stepper< T, B > >", "structxt_1_1is__indexed__stepper_3_01xindexed__stepper_3_01_t_00_01_b_01_4_01_4.html", null ],
      [ "is_iterator", "structxt_1_1is__iterator.html", null ],
      [ "is_iterator< E, void_t< decltype(*std::declval< const E >(), std::declval< const E >()==std::declval< const E >(), std::declval< const E >() !=std::declval< const E >(),++(*std::declval< E * >()),(*std::declval< E * >())++, std::true_type())> >", "structxt_1_1is__iterator_3_01_e_00_01void__t_3_01decltype_07_5std_1_1declval_3_01const_01_e_01_41da12c429c255d2c81e18d875fbe6e98.html", null ],
      [ "is_narrowing_conversion", "structxt_1_1is__narrowing__conversion.html", null ],
      [ "is_not_xdummy_iterator", "structxt_1_1is__not__xdummy__iterator.html", null ],
      [ "is_not_xdummy_iterator< xdummy_iterator< is_const, CT > >", "structxt_1_1is__not__xdummy__iterator_3_01xdummy__iterator_3_01is__const_00_01_c_t_01_4_01_4.html", null ],
      [ "is_reducer_options", "structxt_1_1is__reducer__options.html", null ],
      [ "is_reducer_options_impl", "structxt_1_1is__reducer__options__impl.html", null ],
      [ "is_reducer_options_impl< std::tuple< X... > >", "structxt_1_1is__reducer__options__impl_3_01std_1_1tuple_3_01_x_8_8_8_01_4_01_4.html", null ],
      [ "is_specialization_of", "structxt_1_1is__specialization__of.html", null ],
      [ "is_specialization_of< TT, TT< Ts... > >", "structxt_1_1is__specialization__of_3_01_t_t_00_01_t_t_3_01_ts_8_8_8_01_4_01_4.html", null ],
      [ "is_xoptional_expression", "structxt_1_1is__xoptional__expression.html", null ],
      [ "is_xtensor_expression", "structxt_1_1is__xtensor__expression.html", null ],
      [ "keep_dims_type", "structxt_1_1keep__dims__type.html", null ],
      [ "linear_assigner", "classxt_1_1linear__assigner.html", null ],
      [ "linear_assigner< false >", "classxt_1_1linear__assigner_3_01false_01_4.html", null ],
      [ "make_invalid_type", "structxt_1_1make__invalid__type.html", null ],
      [ "make_void", "structxt_1_1make__void.html", null ],
      [ "memory_range", "structxt_1_1memory__range.html", null ],
      [ "meta_identity", "structxt_1_1meta__identity.html", null ],
      [ "missing_type", "structxt_1_1missing__type.html", null ],
      [ "nested_initializer_list", "structxt_1_1nested__initializer__list.html", null ],
      [ "nested_initializer_list< T, 0 >", "structxt_1_1nested__initializer__list_3_01_t_00_010_01_4.html", null ],
      [ "no_ownership", "structxt_1_1no__ownership.html", null ],
      [ "noalias_proxy", "classxt_1_1noalias__proxy.html", null ],
      [ "norm_type", "structxt_1_1norm__type.html", null ],
      [ "numeric_constants", "structxt_1_1numeric__constants.html", null ],
      [ "overlapping_memory_checker", "structxt_1_1overlapping__memory__checker.html", null ],
      [ "overlapping_memory_checker< Dst, std::enable_if_t< has_memory_address< Dst >::value > >", "structxt_1_1overlapping__memory__checker_3_01_dst_00_01std_1_1enable__if__t_3_01has__memory__add979fb9a8b7b1983c9fb733f357d6c2fa.html", null ],
      [ "overlapping_memory_checker_base", "structxt_1_1overlapping__memory__checker__base.html", null ],
      [ "overlapping_memory_checker_traits", "structxt_1_1overlapping__memory__checker__traits.html", null ],
      [ "overlapping_memory_checker_traits< E >", "structxt_1_1overlapping__memory__checker__traits_3_01_e_01_4.html", null ],
      [ "overlapping_memory_checker_traits< E, std::enable_if_t< has_memory_address< E >::value > >", "structxt_1_1overlapping__memory__checker__traits_3_01_e_00_01std_1_1enable__if__t_3_01has__memor4c750fb1ec54f24555f6fb27c3a9d4ec.html", null ],
      [ "overlapping_memory_checker_traits< E, std::enable_if_t<!has_memory_address< E >::value &&is_crtp_base_of< xview_semantic, E >::value > >", "structxt_1_1overlapping__memory__checker__traits_3_01_e_00_01std_1_1enable__if__t_3_9has__memory9f28c8bceb6a84ea6f46c1fa50db17c9.html", null ],
      [ "overlapping_memory_checker_traits< E, std::enable_if_t<!has_memory_address< E >::value &&is_specialization_of< xbroadcast, E >::value > >", "structxt_1_1overlapping__memory__checker__traits_3_01_e_00_01std_1_1enable__if__t_3_9has__memory25cfd85179f76e6e6f81c9d9e37621a2.html", null ],
      [ "overlapping_memory_checker_traits< E, std::enable_if_t<!has_memory_address< E >::value &&is_specialization_of< xfunction, E >::value > >", "structxt_1_1overlapping__memory__checker__traits_3_01_e_00_01std_1_1enable__if__t_3_9has__memory7631490e58e2e554d47f900b4789ad50.html", null ],
      [ "promote_shape", "structxt_1_1promote__shape.html", null ],
      [ "promote_strides", "structxt_1_1promote__strides.html", null ],
      [ "rebind_container", "structxt_1_1rebind__container.html", null ],
      [ "rebind_container< X, C< T, A > >", "structxt_1_1rebind__container_3_01_x_00_01_c_3_01_t_00_01_a_01_4_01_4.html", null ],
      [ "rebind_container< X, C< T, N > >", "structxt_1_1rebind__container_3_01_x_00_01_c_3_01_t_00_01_n_01_4_01_4.html", null ],
      [ "rebind_container< X, svector< T, N, A, B > >", "structxt_1_1rebind__container_3_01_x_00_01svector_3_01_t_00_01_n_00_01_a_00_01_b_01_4_01_4.html", null ],
      [ "reducer_options", "structxt_1_1reducer__options.html", "structxt_1_1reducer__options" ],
      [ "remove_class", "structxt_1_1remove__class.html", null ],
      [ "remove_class< R(C::*)(Args...) const >", "structxt_1_1remove__class_3_01_r_07_c_1_1_5_08_07_args_8_8_8_08_01const_01_4.html", null ],
      [ "remove_class< R(C::*)(Args...)>", "structxt_1_1remove__class_3_01_r_07_c_1_1_5_08_07_args_8_8_8_08_4.html", null ],
      [ "select_dim_mapping_type", "structxt_1_1select__dim__mapping__type.html", null ],
      [ "select_dim_mapping_type< fixed_shape< I... > >", "structxt_1_1select__dim__mapping__type_3_01fixed__shape_3_01_i_8_8_8_01_4_01_4.html", null ],
      [ "select_iterable_base", "structxt_1_1select__iterable__base.html", null ],
      [ "select_layout", "structxt_1_1select__layout.html", null ],
      [ "sequence_view", "classxt_1_1sequence__view.html", null ],
      [ "squared_norm_type", "structxt_1_1squared__norm__type.html", null ],
      [ "static_dimension", "structxt_1_1static__dimension.html", null ],
      [ "static_string", "structxt_1_1static__string.html", null ],
      [ "stepper_assigner", "classxt_1_1stepper__assigner.html", null ],
      [ "stepper_tools", "structxt_1_1stepper__tools.html", null ],
      [ "strided_loop_assigner", "classxt_1_1strided__loop__assigner.html", null ],
      [ "svector", "classxt_1_1svector.html", null ],
      [ "temporary_container", "structxt_1_1temporary__container.html", null ],
      [ "temporary_container< xbuffer_adaptor< CP, O, A > >", "structxt_1_1temporary__container_3_01xbuffer__adaptor_3_01_c_p_00_01_o_00_01_a_01_4_01_4.html", null ],
      [ "temporary_container< xiterator_adaptor< I, CI > >", "structxt_1_1temporary__container_3_01xiterator__adaptor_3_01_i_00_01_c_i_01_4_01_4.html", null ],
      [ "temporary_container< xiterator_owner_adaptor< C, IG > >", "structxt_1_1temporary__container_3_01xiterator__owner__adaptor_3_01_c_00_01_i_g_01_4_01_4.html", null ],
      [ "temporary_type", "structxt_1_1temporary__type.html", null ],
      [ "temporary_type< T, void_t< typename std::decay_t< T >::temporary_type > >", "structxt_1_1temporary__type_3_01_t_00_01void__t_3_01typename_01std_1_1decay__t_3_01_t_01_4_1_1temporary__type_01_4_01_4.html", null ],
      [ "temporary_type_from_tag", "structxt_1_1temporary__type__from__tag.html", null ],
      [ "temporary_type_from_tag< xtensor_expression_tag, T >", "structxt_1_1temporary__type__from__tag_3_01xtensor__expression__tag_00_01_t_01_4.html", null ],
      [ "tracking_allocator", "structxt_1_1tracking__allocator.html", "structxt_1_1tracking__allocator" ],
      [ "transpose_error", "classxt_1_1transpose__error.html", null ],
      [ "tuple_idx_of", "structxt_1_1tuple__idx__of.html", null ],
      [ "tuple_idx_of_impl", "structxt_1_1tuple__idx__of__impl.html", null ],
      [ "tuple_idx_of_impl< I, T, std::tuple< T, Types... > >", "structxt_1_1tuple__idx__of__impl_3_01_i_00_01_t_00_01std_1_1tuple_3_01_t_00_01_types_8_8_8_01_4_01_4.html", null ],
      [ "tuple_idx_of_impl< I, T, std::tuple< U, Types... > >", "structxt_1_1tuple__idx__of__impl_3_01_i_00_01_t_00_01std_1_1tuple_3_01_u_00_01_types_8_8_8_01_4_01_4.html", null ],
      [ "tuple_idx_of_impl< I, T, std::tuple<> >", "structxt_1_1tuple__idx__of__impl_3_01_i_00_01_t_00_01std_1_1tuple_3_4_01_4.html", null ],
      [ "unaligned_mode", "structxt_1_1unaligned__mode.html", null ],
      [ "uvector", "classxt_1_1uvector.html", null ],
      [ "view_temporary_type", "structxt_1_1view__temporary__type.html", null ],
      [ "xaccessible", "classxt_1_1xaccessible.html", "classxt_1_1xaccessible" ],
      [ "xaccumulator_functor", "structxt_1_1xaccumulator__functor.html", null ],
      [ "xall", "classxt_1_1xall.html", null ],
      [ "xall_tag", "structxt_1_1xall__tag.html", null ],
      [ "xarray_adaptor", "classxt_1_1xarray__adaptor.html", "classxt_1_1xarray__adaptor" ],
      [ "xarray_container", "classxt_1_1xarray__container.html", "classxt_1_1xarray__container" ],
      [ "xassign_traits", "classxt_1_1xassign__traits.html", null ],
      [ "xaxis_iterator", "classxt_1_1xaxis__iterator.html", "classxt_1_1xaxis__iterator" ],
      [ "xaxis_slice_iterator", "classxt_1_1xaxis__slice__iterator.html", "classxt_1_1xaxis__slice__iterator" ],
      [ "xblockwise_reducer", "classxt_1_1xblockwise__reducer.html", null ],
      [ "xbounded_iterator", "classxt_1_1xbounded__iterator.html", null ],
      [ "xbroadcast", "classxt_1_1xbroadcast.html", "classxt_1_1xbroadcast" ],
      [ "xbuffer_adaptor", "classxt_1_1xbuffer__adaptor.html", null ],
      [ "xbuffer_adaptor_base", "classxt_1_1xbuffer__adaptor__base.html", null ],
      [ "xchunk_iterator", "classxt_1_1xchunk__iterator.html", null ],
      [ "xchunked_array", "classxt_1_1xchunked__array.html", null ],
      [ "xchunked_assigner", "classxt_1_1xchunked__assigner.html", null ],
      [ "xchunked_semantic", "classxt_1_1xchunked__semantic.html", null ],
      [ "xchunked_view", "classxt_1_1xchunked__view.html", null ],
      [ "xclosure", "structxt_1_1xclosure.html", null ],
      [ "xclosure< E, disable_xexpression< std::decay_t< E > > >", "structxt_1_1xclosure_3_01_e_00_01disable__xexpression_3_01std_1_1decay__t_3_01_e_01_4_01_4_01_4.html", null ],
      [ "xclosure< xshared_expression< E >, std::enable_if_t< true > >", "structxt_1_1xclosure_3_01xshared__expression_3_01_e_01_4_00_01std_1_1enable__if__t_3_01true_01_4_01_4.html", null ],
      [ "xconst_accessible", "classxt_1_1xconst__accessible.html", "classxt_1_1xconst__accessible" ],
      [ "xconst_iterable", "classxt_1_1xconst__iterable.html", "classxt_1_1xconst__iterable" ],
      [ "xcontainer", "classxt_1_1xcontainer.html", "classxt_1_1xcontainer" ],
      [ "xcontainer_inner_types", "structxt_1_1xcontainer__inner__types.html", null ],
      [ "xcontainer_inner_types< xarray_adaptor< EC, L, SC, Tag > >", "structxt_1_1xcontainer__inner__types_3_01xarray__adaptor_3_01_e_c_00_01_l_00_01_s_c_00_01_tag_01_4_01_4.html", null ],
      [ "xcontainer_inner_types< xarray_container< EC, L, SC, Tag > >", "structxt_1_1xcontainer__inner__types_3_01xarray__container_3_01_e_c_00_01_l_00_01_s_c_00_01_tag_01_4_01_4.html", null ],
      [ "xcontainer_inner_types< xbroadcast< CT, X > >", "structxt_1_1xcontainer__inner__types_3_01xbroadcast_3_01_c_t_00_01_x_01_4_01_4.html", null ],
      [ "xcontainer_inner_types< xchunked_array< chunk_storage > >", "structxt_1_1xcontainer__inner__types_3_01xchunked__array_3_01chunk__storage_01_4_01_4.html", null ],
      [ "xcontainer_inner_types< xdynamic_view< CT, S, L, FST > >", "structxt_1_1xcontainer__inner__types_3_01xdynamic__view_3_01_c_t_00_01_s_00_01_l_00_01_f_s_t_01_4_01_4.html", null ],
      [ "xcontainer_inner_types< xfixed_adaptor< EC, S, L, SH, Tag > >", "structxt_1_1xcontainer__inner__types_3_01xfixed__adaptor_3_01_e_c_00_01_s_00_01_l_00_01_s_h_00_01_tag_01_4_01_4.html", null ],
      [ "xcontainer_inner_types< xfixed_container< ET, S, L, SH, Tag > >", "structxt_1_1xcontainer__inner__types_3_01xfixed__container_3_01_e_t_00_01_s_00_01_l_00_01_s_h_00_01_tag_01_4_01_4.html", null ],
      [ "xcontainer_inner_types< xfunction< F, CT... > >", "structxt_1_1xcontainer__inner__types_3_01xfunction_3_01_f_00_01_c_t_8_8_8_01_4_01_4.html", null ],
      [ "xcontainer_inner_types< xfunctor_adaptor< F, CT > >", "structxt_1_1xcontainer__inner__types_3_01xfunctor__adaptor_3_01_f_00_01_c_t_01_4_01_4.html", null ],
      [ "xcontainer_inner_types< xfunctor_view< F, CT > >", "structxt_1_1xcontainer__inner__types_3_01xfunctor__view_3_01_f_00_01_c_t_01_4_01_4.html", null ],
      [ "xcontainer_inner_types< xgenerator< C, R, S > >", "structxt_1_1xcontainer__inner__types_3_01xgenerator_3_01_c_00_01_r_00_01_s_01_4_01_4.html", null ],
      [ "xcontainer_inner_types< xindex_view< CT, I > >", "structxt_1_1xcontainer__inner__types_3_01xindex__view_3_01_c_t_00_01_i_01_4_01_4.html", null ],
      [ "xcontainer_inner_types< xmasked_view< CTD, CTM > >", "structxt_1_1xcontainer__inner__types_3_01xmasked__view_3_01_c_t_d_00_01_c_t_m_01_4_01_4.html", null ],
      [ "xcontainer_inner_types< xoptional_assembly< VE, FE > >", "structxt_1_1xcontainer__inner__types_3_01xoptional__assembly_3_01_v_e_00_01_f_e_01_4_01_4.html", null ],
      [ "xcontainer_inner_types< xoptional_assembly_adaptor< VEC, FEC > >", "structxt_1_1xcontainer__inner__types_3_01xoptional__assembly__adaptor_3_01_v_e_c_00_01_f_e_c_01_4_01_4.html", null ],
      [ "xcontainer_inner_types< xreducer< F, CT, X, O > >", "structxt_1_1xcontainer__inner__types_3_01xreducer_3_01_f_00_01_c_t_00_01_x_00_01_o_01_4_01_4.html", null ],
      [ "xcontainer_inner_types< xscalar< CT > >", "structxt_1_1xcontainer__inner__types_3_01xscalar_3_01_c_t_01_4_01_4.html", null ],
      [ "xcontainer_inner_types< xstrided_view< CT, S, L, FST > >", "structxt_1_1xcontainer__inner__types_3_01xstrided__view_3_01_c_t_00_01_s_00_01_l_00_01_f_s_t_01_4_01_4.html", null ],
      [ "xcontainer_inner_types< xtensor_adaptor< EC, N, L, Tag > >", "structxt_1_1xcontainer__inner__types_3_01xtensor__adaptor_3_01_e_c_00_01_n_00_01_l_00_01_tag_01_4_01_4.html", null ],
      [ "xcontainer_inner_types< xtensor_container< EC, N, L, Tag > >", "structxt_1_1xcontainer__inner__types_3_01xtensor__container_3_01_e_c_00_01_n_00_01_l_00_01_tag_01_4_01_4.html", null ],
      [ "xcontainer_inner_types< xtensor_view< EC, N, L, Tag > >", "structxt_1_1xcontainer__inner__types_3_01xtensor__view_3_01_e_c_00_01_n_00_01_l_00_01_tag_01_4_01_4.html", null ],
      [ "xcontainer_inner_types< xview< CT, S... > >", "structxt_1_1xcontainer__inner__types_3_01xview_3_01_c_t_00_01_s_8_8_8_01_4_01_4.html", null ],
      [ "xcontainer_iterable_types", "structxt_1_1xcontainer__iterable__types.html", null ],
      [ "xcontainer_semantic", "classxt_1_1xcontainer__semantic.html", "classxt_1_1xcontainer__semantic" ],
      [ "xcontiguous_iterable", "classxt_1_1xcontiguous__iterable.html", "classxt_1_1xcontiguous__iterable" ],
      [ "xcsv_config", "structxt_1_1xcsv__config.html", null ],
      [ "xdrop_slice", "classxt_1_1xdrop__slice.html", null ],
      [ "xdummy_iterator", "classxt_1_1xdummy__iterator.html", null ],
      [ "xdynamic_view", "classxt_1_1xdynamic__view.html", "classxt_1_1xdynamic__view" ],
      [ "xellipsis_tag", "structxt_1_1xellipsis__tag.html", null ],
      [ "xexpression", "classxt_1_1xexpression.html", "classxt_1_1xexpression" ],
      [ "xexpression_assigner", "classxt_1_1xexpression__assigner.html", null ],
      [ "xexpression_assigner_base", "classxt_1_1xexpression__assigner__base.html", null ],
      [ "xexpression_assigner_base< xoptional_expression_tag >", "classxt_1_1xexpression__assigner__base_3_01xoptional__expression__tag_01_4.html", null ],
      [ "xexpression_assigner_base< xtensor_expression_tag >", "classxt_1_1xexpression__assigner__base_3_01xtensor__expression__tag_01_4.html", null ],
      [ "xexpression_holder", "classxt_1_1xexpression__holder.html", null ],
      [ "xexpression_tag", "structxt_1_1xexpression__tag.html", null ],
      [ "xfiltration", "classxt_1_1xfiltration.html", "classxt_1_1xfiltration" ],
      [ "xfixed_adaptor", "classxt_1_1xfixed__adaptor.html", "classxt_1_1xfixed__adaptor" ],
      [ "xfixed_container", "classxt_1_1xfixed__container.html", "classxt_1_1xfixed__container" ],
      [ "xfunction", "classxt_1_1xfunction.html", "classxt_1_1xfunction" ],
      [ "xfunction_cache", "structxt_1_1xfunction__cache.html", null ],
      [ "xfunction_iterator", "classxt_1_1xfunction__iterator.html", null ],
      [ "xfunction_stepper", "classxt_1_1xfunction__stepper.html", null ],
      [ "xfunctor_adaptor", "classxt_1_1xfunctor__adaptor.html", "classxt_1_1xfunctor__adaptor" ],
      [ "xfunctor_applier_base", "classxt_1_1xfunctor__applier__base.html", "classxt_1_1xfunctor__applier__base" ],
      [ "xfunctor_iterator", "classxt_1_1xfunctor__iterator.html", null ],
      [ "xfunctor_stepper", "classxt_1_1xfunctor__stepper.html", null ],
      [ "xfunctor_view", "classxt_1_1xfunctor__view.html", "classxt_1_1xfunctor__view" ],
      [ "xfunctor_view_temporary_type", "structxt_1_1xfunctor__view__temporary__type.html", null ],
      [ "xgenerator", "classxt_1_1xgenerator.html", "classxt_1_1xgenerator" ],
      [ "xindex_view", "classxt_1_1xindex__view.html", "classxt_1_1xindex__view" ],
      [ "xindexed_stepper", "classxt_1_1xindexed__stepper.html", null ],
      [ "xinitial", "structxt_1_1xinitial.html", null ],
      [ "xiterable", "classxt_1_1xiterable.html", "classxt_1_1xiterable" ],
      [ "xiterable_inner_types", "structxt_1_1xiterable__inner__types.html", null ],
      [ "xiterable_inner_types< xarray_adaptor< EC, L, SC, Tag > >", "structxt_1_1xiterable__inner__types_3_01xarray__adaptor_3_01_e_c_00_01_l_00_01_s_c_00_01_tag_01_4_01_4.html", null ],
      [ "xiterable_inner_types< xarray_container< EC, L, SC, Tag > >", "structxt_1_1xiterable__inner__types_3_01xarray__container_3_01_e_c_00_01_l_00_01_s_c_00_01_tag_01_4_01_4.html", null ],
      [ "xiterable_inner_types< xbroadcast< CT, X > >", "structxt_1_1xiterable__inner__types_3_01xbroadcast_3_01_c_t_00_01_x_01_4_01_4.html", null ],
      [ "xiterable_inner_types< xchunked_array< chunk_storage > >", "structxt_1_1xiterable__inner__types_3_01xchunked__array_3_01chunk__storage_01_4_01_4.html", null ],
      [ "xiterable_inner_types< xdynamic_view< CT, S, L, FST > >", "structxt_1_1xiterable__inner__types_3_01xdynamic__view_3_01_c_t_00_01_s_00_01_l_00_01_f_s_t_01_4_01_4.html", null ],
      [ "xiterable_inner_types< xfixed_adaptor< EC, S, L, SH, Tag > >", "structxt_1_1xiterable__inner__types_3_01xfixed__adaptor_3_01_e_c_00_01_s_00_01_l_00_01_s_h_00_01_tag_01_4_01_4.html", null ],
      [ "xiterable_inner_types< xfixed_container< ET, S, L, SH, Tag > >", "structxt_1_1xiterable__inner__types_3_01xfixed__container_3_01_e_t_00_01_s_00_01_l_00_01_s_h_00_01_tag_01_4_01_4.html", null ],
      [ "xiterable_inner_types< xfunction< F, CT... > >", "structxt_1_1xiterable__inner__types_3_01xfunction_3_01_f_00_01_c_t_8_8_8_01_4_01_4.html", null ],
      [ "xiterable_inner_types< xgenerator< C, R, S > >", "structxt_1_1xiterable__inner__types_3_01xgenerator_3_01_c_00_01_r_00_01_s_01_4_01_4.html", null ],
      [ "xiterable_inner_types< xindex_view< CT, I > >", "structxt_1_1xiterable__inner__types_3_01xindex__view_3_01_c_t_00_01_i_01_4_01_4.html", null ],
      [ "xiterable_inner_types< xmasked_view< CTD, CTM > >", "structxt_1_1xiterable__inner__types_3_01xmasked__view_3_01_c_t_d_00_01_c_t_m_01_4_01_4.html", null ],
      [ "xiterable_inner_types< xoptional_assembly< VE, FE > >", "structxt_1_1xiterable__inner__types_3_01xoptional__assembly_3_01_v_e_00_01_f_e_01_4_01_4.html", null ],
      [ "xiterable_inner_types< xoptional_assembly_adaptor< VEC, FEC > >", "structxt_1_1xiterable__inner__types_3_01xoptional__assembly__adaptor_3_01_v_e_c_00_01_f_e_c_01_4_01_4.html", null ],
      [ "xiterable_inner_types< xreducer< F, CT, X, O > >", "structxt_1_1xiterable__inner__types_3_01xreducer_3_01_f_00_01_c_t_00_01_x_00_01_o_01_4_01_4.html", null ],
      [ "xiterable_inner_types< xrepeat< CT, R > >", "structxt_1_1xiterable__inner__types_3_01xrepeat_3_01_c_t_00_01_r_01_4_01_4.html", null ],
      [ "xiterable_inner_types< xscalar< CT > >", "structxt_1_1xiterable__inner__types_3_01xscalar_3_01_c_t_01_4_01_4.html", null ],
      [ "xiterable_inner_types< xstrided_view< CT, S, L, FST > >", "structxt_1_1xiterable__inner__types_3_01xstrided__view_3_01_c_t_00_01_s_00_01_l_00_01_f_s_t_01_4_01_4.html", null ],
      [ "xiterable_inner_types< xtensor_adaptor< EC, N, L, Tag > >", "structxt_1_1xiterable__inner__types_3_01xtensor__adaptor_3_01_e_c_00_01_n_00_01_l_00_01_tag_01_4_01_4.html", null ],
      [ "xiterable_inner_types< xtensor_container< EC, N, L, Tag > >", "structxt_1_1xiterable__inner__types_3_01xtensor__container_3_01_e_c_00_01_n_00_01_l_00_01_tag_01_4_01_4.html", null ],
      [ "xiterable_inner_types< xtensor_view< EC, N, L, Tag > >", "structxt_1_1xiterable__inner__types_3_01xtensor__view_3_01_e_c_00_01_n_00_01_l_00_01_tag_01_4_01_4.html", null ],
      [ "xiterable_inner_types< xview< CT, S... > >", "structxt_1_1xiterable__inner__types_3_01xview_3_01_c_t_00_01_s_8_8_8_01_4_01_4.html", null ],
      [ "xiterator", "classxt_1_1xiterator.html", null ],
      [ "xiterator_adaptor", "classxt_1_1xiterator__adaptor.html", null ],
      [ "xiterator_owner_adaptor", "classxt_1_1xiterator__owner__adaptor.html", null ],
      [ "xkeep_slice", "classxt_1_1xkeep__slice.html", null ],
      [ "xmasked_value", "classxt_1_1xmasked__value.html", null ],
      [ "xmasked_view", "classxt_1_1xmasked__view.html", "classxt_1_1xmasked__view" ],
      [ "xmasked_view_stepper", "classxt_1_1xmasked__view__stepper.html", null ],
      [ "xmultiindex_iterator", "classxt_1_1xmultiindex__iterator.html", null ],
      [ "xnewaxis", "classxt_1_1xnewaxis.html", null ],
      [ "xnewaxis_tag", "structxt_1_1xnewaxis__tag.html", null ],
      [ "xoptional_assembly", "classxt_1_1xoptional__assembly.html", "classxt_1_1xoptional__assembly" ],
      [ "xoptional_assembly_adaptor", "classxt_1_1xoptional__assembly__adaptor.html", "classxt_1_1xoptional__assembly__adaptor" ],
      [ "xoptional_assembly_base", "classxt_1_1xoptional__assembly__base.html", "classxt_1_1xoptional__assembly__base" ],
      [ "xoptional_assembly_linear_iterator", "classxt_1_1xoptional__assembly__linear__iterator.html", null ],
      [ "xoptional_assembly_linear_iterator_traits", "structxt_1_1xoptional__assembly__linear__iterator__traits.html", null ],
      [ "xoptional_assembly_stepper", "classxt_1_1xoptional__assembly__stepper.html", null ],
      [ "xoptional_assembly_storage", "classxt_1_1xoptional__assembly__storage.html", null ],
      [ "xoptional_comparable", "structxt_1_1xoptional__comparable.html", null ],
      [ "xoptional_expression_tag", "structxt_1_1xoptional__expression__tag.html", null ],
      [ "xproxy_inner_types", "structxt_1_1xproxy__inner__types.html", null ],
      [ "xrange", "classxt_1_1xrange.html", null ],
      [ "xrange_adaptor", "structxt_1_1xrange__adaptor.html", null ],
      [ "xreducer", "classxt_1_1xreducer.html", "classxt_1_1xreducer" ],
      [ "xreducer_functors", "structxt_1_1xreducer__functors.html", null ],
      [ "xreducer_shape_type", "structxt_1_1xreducer__shape__type.html", null ],
      [ "xreducer_shape_type< fixed_shape< I... >, fixed_shape< J... >, O >", "structxt_1_1xreducer__shape__type_3_01fixed__shape_3_01_i_8_8_8_01_4_00_01fixed__shape_3_01_j_8_8_8_01_4_00_01_o_01_4.html", null ],
      [ "xreducer_shape_type< fixed_shape< I... >, std::array< I2, N2 >, std::false_type >", "structxt_1_1xreducer__shape__type_3_01fixed__shape_3_01_i_8_8_8_01_4_00_01std_1_1array_3_01_i2_0113732d5b63b22c20cb89d3a7b591d8f.html", null ],
      [ "xreducer_shape_type< fixed_shape< I... >, std::array< I2, N2 >, std::true_type >", "structxt_1_1xreducer__shape__type_3_01fixed__shape_3_01_i_8_8_8_01_4_00_01std_1_1array_3_01_i2_06680ea94625f20ef8cb3bcfb83eeaa0c.html", null ],
      [ "xreducer_shape_type< std::array< I1, N1 >, std::array< I2, N2 >, std::false_type >", "structxt_1_1xreducer__shape__type_3_01std_1_1array_3_01_i1_00_01_n1_01_4_00_01std_1_1array_3_01_f0fe2e231e25d4e5852b877ba4b36e02.html", null ],
      [ "xreducer_shape_type< std::array< I1, N1 >, std::array< I2, N2 >, std::true_type >", "structxt_1_1xreducer__shape__type_3_01std_1_1array_3_01_i1_00_01_n1_01_4_00_01std_1_1array_3_01_c677fa36e83a1c564b51c5abf4a0c7d9.html", null ],
      [ "xreducer_stepper", "classxt_1_1xreducer__stepper.html", null ],
      [ "xrepeat", "classxt_1_1xrepeat.html", "classxt_1_1xrepeat" ],
      [ "xrepeat_stepper", "classxt_1_1xrepeat__stepper.html", null ],
      [ "xscalar", "classxt_1_1xscalar.html", "classxt_1_1xscalar" ],
      [ "xscalar_stepper", "classxt_1_1xscalar__stepper.html", null ],
      [ "xsemantic_base", "classxt_1_1xsemantic__base.html", "classxt_1_1xsemantic__base" ],
      [ "xsharable_expression", "classxt_1_1xsharable__expression.html", null ],
      [ "xshared_expression", "classxt_1_1xshared__expression.html", "classxt_1_1xshared__expression" ],
      [ "xslice", "classxt_1_1xslice.html", null ],
      [ "xstepped_range", "classxt_1_1xstepped__range.html", null ],
      [ "xstepper", "classxt_1_1xstepper.html", null ],
      [ "xstrided_container", "classxt_1_1xstrided__container.html", "classxt_1_1xstrided__container" ],
      [ "xstrided_view", "classxt_1_1xstrided__view.html", "classxt_1_1xstrided__view" ],
      [ "xstrided_view_base", "classxt_1_1xstrided__view__base.html", "classxt_1_1xstrided__view__base" ],
      [ "xtensor_adaptor", "classxt_1_1xtensor__adaptor.html", "classxt_1_1xtensor__adaptor" ],
      [ "xtensor_container", "classxt_1_1xtensor__container.html", "classxt_1_1xtensor__container" ],
      [ "xtensor_expression_tag", "structxt_1_1xtensor__expression__tag.html", null ],
      [ "xtensor_view", "classxt_1_1xtensor__view.html", "classxt_1_1xtensor__view" ],
      [ "xvectorizer", "classxt_1_1xvectorizer.html", null ],
      [ "xview", "classxt_1_1xview.html", "classxt_1_1xview" ],
      [ "xview_semantic", "classxt_1_1xview__semantic.html", "classxt_1_1xview__semantic" ],
      [ "xview_shape_type", "structxt_1_1xview__shape__type.html", null ],
      [ "xview_shape_type< fixed_shape< I... >, S... >", "structxt_1_1xview__shape__type_3_01fixed__shape_3_01_i_8_8_8_01_4_00_01_s_8_8_8_01_4.html", null ],
      [ "xview_shape_type< std::array< I, L >, S... >", "structxt_1_1xview__shape__type_3_01std_1_1array_3_01_i_00_01_l_01_4_00_01_s_8_8_8_01_4.html", null ],
      [ "xview_stepper", "classxt_1_1xview__stepper.html", null ]
    ] ],
    [ "xt_simd", null, [
      [ "aligned_allocator", "classxt__simd_1_1aligned__allocator.html", null ],
      [ "aligned_mode", "structxt__simd_1_1aligned__mode.html", null ],
      [ "allocator_alignment", "structxt__simd_1_1allocator__alignment.html", null ],
      [ "container_alignment", "structxt__simd_1_1container__alignment.html", null ],
      [ "is_batch_bool", "structxt__simd_1_1is__batch__bool.html", null ],
      [ "is_batch_complex", "structxt__simd_1_1is__batch__complex.html", null ],
      [ "revert_simd_traits", "structxt__simd_1_1revert__simd__traits.html", null ],
      [ "simd_condition", "structxt__simd_1_1simd__condition.html", null ],
      [ "simd_traits", "structxt__simd_1_1simd__traits.html", null ],
      [ "unaligned_mode", "structxt__simd_1_1unaligned__mode.html", null ]
    ] ],
    [ "xtl", null, [
      [ "conjunction", "structxtl_1_1conjunction.html", null ]
    ] ]
];