var topics =
[
    [ "Xt_xchunked_array", "group__xt__xchunked__array.html", "group__xt__xchunked__array" ],
    [ "Adaptors of STL-like containers", "group__xt__xadapt.html", "group__xt__xadapt" ],
    [ "Xt_xeval", "group__xt__xeval.html", "group__xt__xeval" ],
    [ "Basic functions", "group__basic__functions.html", "group__basic__functions" ],
    [ "Exponential functions", "group__exp__functions.html", "group__exp__functions" ],
    [ "Power functions", "group__pow__functions.html", "group__pow__functions" ],
    [ "Trigonometric function", "group__trigo__functions.html", "group__trigo__functions" ],
    [ "Hyperbolic functions", "group__hyper__functions.html", "group__hyper__functions" ],
    [ "Error and gamma functions", "group__err__functions.html", "group__err__functions" ],
    [ "Nearest integer floating point operations", "group__nearint__functions.html", "group__nearint__functions" ],
    [ "Classification functions", "group__classif__functions.html", "group__classif__functions" ],
    [ "reducing functions", "group__red__functions.html", "group__red__functions" ],
    [ "accumulating functions", "group__acc__functions.html", "group__acc__functions" ],
    [ "nan functions", "group__nan__functions.html", "group__nan__functions" ],
    [ "Arithmetic operators", "group__arithmetic__operators.html", "group__arithmetic__operators" ],
    [ "Logical operators", "group__logical__operators.html", "group__logical__operators" ],
    [ "Bitwise operators", "group__bitwise__operators.html", "group__bitwise__operators" ],
    [ "Comparison operators", "group__comparison__operators.html", "group__comparison__operators" ],
    [ "Casting operators", "group__casting__operators.html", "group__casting__operators" ],
    [ "Support functions to get/check a shape array.", "group__xt__xshape.html", "group__xt__xshape" ],
    [ "Support functions swich between array indices and flat indices", "group__xt__xstrides.html", "group__xt__xstrides" ],
    [ "Xt_xcomplex", "group__xt__xcomplex.html", "group__xt__xcomplex" ],
    [ "Xt_xmanipulation", "group__xt__xmanipulation.html", "group__xt__xmanipulation" ],
    [ "Sorting functions.", "group__xt__xsort.html", "group__xt__xsort" ],
    [ "Xt_xfunctor_view", "group__xt__xfunctor__view.html", "group__xt__xfunctor__view" ]
];