var searchData=
[
  ['select_5fdim_5fmapping_5ftype_0',['select_dim_mapping_type',['../structxt_1_1select__dim__mapping__type.html',1,'xt']]],
  ['select_5fdim_5fmapping_5ftype_3c_20fixed_5fshape_3c_20i_2e_2e_2e_20_3e_20_3e_1',['select_dim_mapping_type&lt; fixed_shape&lt; I... &gt; &gt;',['../structxt_1_1select__dim__mapping__type_3_01fixed__shape_3_01_i_8_8_8_01_4_01_4.html',1,'xt']]],
  ['select_5fdim_5fmapping_5ftype_3c_20inner_5fshape_5ftype_20_3e_2',['select_dim_mapping_type&lt; inner_shape_type &gt;',['../structxt_1_1select__dim__mapping__type.html',1,'xt']]],
  ['select_5fiterable_5fbase_3',['select_iterable_base',['../structxt_1_1select__iterable__base.html',1,'xt']]],
  ['select_5flayout_4',['select_layout',['../structxt_1_1select__layout.html',1,'xt']]],
  ['sequence_5fview_5',['sequence_view',['../classxt_1_1sequence__view.html',1,'xt']]],
  ['sign_5ffun_6',['sign_fun',['../structxt_1_1math_1_1sign__fun.html',1,'xt::math']]],
  ['sign_5fimpl_7',['sign_impl',['../structxt_1_1math_1_1sign__impl.html',1,'xt::math']]],
  ['sign_5fimpl_3c_20xtl_3a_3axoptional_3c_20t_2c_20b_20_3e_20_3e_8',['sign_impl&lt; xtl::xoptional&lt; T, B &gt; &gt;',['../structxt_1_1math_1_1sign__impl_3_01xtl_1_1xoptional_3_01_t_00_01_b_01_4_01_4.html',1,'xt::math']]],
  ['simd_5fcondition_9',['simd_condition',['../structxt__simd_1_1simd__condition.html',1,'xt_simd']]],
  ['simd_5ftraits_10',['simd_traits',['../structxt__simd_1_1simd__traits.html',1,'xt_simd']]],
  ['sin_5ffun_11',['sin_fun',['../structxt_1_1math_1_1sin__fun.html',1,'xt::math']]],
  ['sinh_5ffun_12',['sinh_fun',['../structxt_1_1math_1_1sinh__fun.html',1,'xt::math']]],
  ['sqrt_5ffun_13',['sqrt_fun',['../structxt_1_1math_1_1sqrt__fun.html',1,'xt::math']]],
  ['squared_5fnorm_5ftype_14',['squared_norm_type',['../structxt_1_1squared__norm__type.html',1,'xt']]],
  ['static_5fdimension_15',['static_dimension',['../structxt_1_1static__dimension.html',1,'xt']]],
  ['static_5fstring_16',['static_string',['../structxt_1_1static__string.html',1,'xt']]],
  ['stepper_5fassigner_17',['stepper_assigner',['../classxt_1_1stepper__assigner.html',1,'xt']]],
  ['stepper_5ftools_18',['stepper_tools',['../structxt_1_1stepper__tools.html',1,'xt']]],
  ['strided_5floop_5fassigner_19',['strided_loop_assigner',['../classxt_1_1strided__loop__assigner.html',1,'xt']]],
  ['svector_20',['svector',['../classxt_1_1svector.html',1,'xt']]],
  ['svector_3c_20size_5ftype_20_3e_21',['svector&lt; size_type &gt;',['../classxt_1_1svector.html',1,'xt']]]
];
