set(AVAILABLE_SANITIZERS "address;leak;memory;thread;undefined")
OPTION(USE_SANITIZER "Enable sanitizer(s). Options are: ${AVAILABLE_SANITIZERS}. Case insensitive; multiple options delimited by comma or space possible." "")
string(TOLOWER "${USE_SANITIZER}" USE_SANITIZER)

if(USE_SANITIZER AND NOT (CMAKE_BUILD_TYPE IN_LIST "Debug;RelWithDebInfo"))
    message(FATAL_ERROR "❌ Sanitizer only supported in Debug and RelWithDebInfo build types. Current: ${CMAKE_BUILD_TYPE}")
endif()

if(USE_SANITIZER)
    if(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
        set(CMAKE_MSVC_DEBUG_INFORMATION_FORMAT "$<IF:$<AND:$<C_COMPILER_ID:MSVC>,$<CXX_COMPILER_ID:MSVC>>,$<$<CONFIG:Debug,RelWithDebInfo>:EditAndContinue>,$<$<CONFIG:Debug,RelWithDebInfo>:ProgramDatabase>>")

        if(USE_SANITIZER MATCHES "address")
            string(APPEND CMAKE_CXX_FLAGS " /fsanitize=address /D_DISABLE_VECTOR_ANNOTATION /D_DISABLE_STRING_ANNOTATION")
            string(APPEND CMAKE_EXE_LINKER_FLAGS " /fsanitize=address")
        else()
            message(FATAL_ERROR "❌ Sanitizer not supported by MSVC: ${USE_SANITIZER}. It only supports 'address'.")
        endif()
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL "Clang" AND CMAKE_CXX_COMPILER_FRONTEND_VARIANT STREQUAL "MSVC")
        if(USE_SANITIZER MATCHES "address")
            string(APPEND CMAKE_CXX_FLAGS " /fsanitize=address /D_DISABLE_VECTOR_ANNOTATION /D_DISABLE_STRING_ANNOTATION")
            string(APPEND CMAKE_EXE_LINKER_FLAGS " /fsanitize=address")
        else()
            message(FATAL_ERROR "❌ Sanitizer not supported by Clang-MSVC: ${USE_SANITIZER}. It only supports 'address'.")
        endif()
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL "Clang" OR CMAKE_CXX_COMPILER_ID STREQUAL "AppleClang" OR CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
        foreach(sanitizer ${USE_SANITIZER})
            if(NOT ${sanitizer} IN_LIST AVAILABLE_SANITIZERS)
                message(FATAL_ERROR "❌ Sanitizer not supported: ${sanitizer}. It should be one of: ${AVAILABLE_SANITIZERS}.")
            endif()
            string(APPEND CMAKE_CXX_FLAGS " -fsanitize=${sanitizer}")
            string(APPEND CMAKE_EXE_LINKER_FLAGS " -fsanitize=${sanitizer}")
            if(${sanitizer} MATCHES "memory")
                string(APPEND CMAKE_CXX_FLAGS " -fsanitize-memory-track-origins -fPIE -pie")
                string(APPEND CMAKE_EXE_LINKER_FLAGS " -fsanitize-memory-track-origins -fPIE -pie")
            endif()
        endforeach()
        string(APPEND CMAKE_CXX_FLAGS " -fno-omit-frame-pointer")
    else()
        message(FATAL_ERROR "❌ Sanitizer: Unsupported compiler: ${CMAKE_CXX_COMPILER_ID}")
    endif()

    message(STATUS "🔍 Using sanitizer: ${USE_SANITIZER}")
endif()
