name: CodSpeed

on:
  push:
    branches: [master]
  pull_request:
  # Allow CodSpeed to trigger backtest performance analysis
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.job }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -e -l {0}

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set conda environment
        uses: mamba-org/setup-micromamba@main
        with:
          environment-name: myenv
          environment-file: environment-dev.yml
          init-shell: bash
          cache-downloads: true

      - name: Build benchmarks
        run: |
          cmake -G Ninja -Bbuild \
            -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX \
            -DBUILD_BENCHMARK=ON \
            -DXTENSOR_USE_XSIMD=ON \
            -DCODSPEED_MODE=simulation
          cmake --build build --target benchmark_xtensor --parallel 8

      - name: Run benchmarks
        uses: CodSpeedHQ/action@v4
        with:
          mode: simulation
          run: ./build/benchmark/benchmark_xtensor
